### ISSUE TITLE
[Accessibility] Readme Absulte Path

### ISSUE THREAD

**Issue by AnzhiZhang** [TISUnion/PrimeBackup#11]
I've noticed you have marked readme files from this repo as introductions in the [PluginCatalogue](https://github.com/MCDReforged/PluginCatalogue). However, the path of the screenshot and language switch links are relative paths:

```
[English](README.md) | **中文**
![!!pb command](docs/img/pb_welcome.zh.png)
```

Therefore, the link and picture are not available in the plugin catalog.
![image](https://github.com/TISUnion/PrimeBackup/assets/37402126/2bf18d1c-f336-4481-b4b3-aa78a3d69498)

May I kindly advice you set these two links to absolute paths to improve the user experience when exploring the plugin catalogue. Your help will significantly benefit a wide range of users around the world and build our community much better!

**Comment by Fallen-Breath** [comment]
Fixed on the plugin catalogue side

https://github.com/MCDReforged/PluginCatalogue/commit/c426edcbc1add6015edb626dc939b7f3e3a80572
