### ISSUE TITLE
list有备份不显示

### ISSUE THREAD

**Issue by JKGouZi** [TISUnion/PrimeBackup#14]
![微信截图_20240204121240](https://github.com/TISUnion/PrimeBackup/assets/61960687/dc8c2078-094f-4abb-b7f0-0abab2f70b0e)
![微信图片_20240204121257](https://github.com/TISUnion/PrimeBackup/assets/61960687/eaf12f21-51ee-4557-b645-959a47a2e193)

**Comment by Fallen-Breath** [comment]
你可以使用 ｀!!pb list -a｀来展示所有类型的备份

**Comment by JKGouZi** [comment]
还是这样

**Comment by Fallen-Breath** [comment]
请提供完整的上下文以供分析，包括：

**环境**

- PrimeBackup 版本
- MCDR 版本
- Python 版本
- 操作系统类型
- MC 服务端种类

**表现**

- 在控制台、游戏内输入 `!!pb list -a` 后，MCDR 的输出内容

除此之外，请确保 MCDR、PrimeBackup 均被正确地配置，以及 MC 服务端 / 客户端并不含有任何阻止富文本显示的 mod / 插件

如果方便，你可以提供一份从 0 开始的复现方法，从全新环境开始配置 PrimeBackup 插件，进行 xxx 操作后将会触发本 issue

**Comment by JKGouZi** [comment]
PrimeBackup 版本 1.6.3
MCDR 版本 2.12.3
Python 版本 3.12.1
操作系统类型 Windows Server 2022 Datacenter
MC服务器种类 fabric端

**Comment by Fallen-Breath** [comment]
无法复现。环境如下：

- PrimeBackup v1.6.3
- MCDR 2.12.3
- Python 3.12.1
- 操作系统：Windows Server 2022 Datacenter

![image](https://github.com/TISUnion/PrimeBackup/assets/28978806/f8d388d4-9247-4f2b-9881-19e581207447)

**Comment by JKGouZi** [comment]
我这服务器 自己电脑开都还是这样 兄弟要是方便的话把整个包发我我试一下

**Comment by JKGouZi** [comment]
我这服务器 自己电脑开都还是这样 兄弟要是方便的话把整个包发我我试一下

**Comment by Fallen-Breath** [comment]
我的环境中并不存在所谓可以整个包发一下的方式。以正确方式安装的 操作系统、python、java、MCDR 的环境组合，不存在整合包这一种形式的发布形式

**Comment by JKGouZi** [comment]
我心思是我MCDR端没配置好 但我完全按照文档来的

**Comment by Fallen-Breath** [comment]
如 https://github.com/TISUnion/PrimeBackup/issues/14#issuecomment-1925656265 所述，如果因未正确配置 MCDR、PB 而引起的本 issue，则该 issue 为用户问题，将关闭；如果在正确配置的某些环境下可以复现该 issue，则给清楚详细完整的，环境搭建+ 复现步骤

**Comment by AnzhiZhang** [comment]
@JKGouZi 建议提供：

1. 执行 `!!pb list -a` 后的结果截图或文本
2. 直接上传你的备份信息数据库，以及服务端和MCDR日志，还有 PB 插件的配置文件

以上建议可能帮助作者在你表达能力欠缺的情况下确定问题和找到原因

**Comment by cdqtzrc** [comment]
问题似乎来自客户端，去掉OMMC后就可以正常显示（在1.20.4中测试）

**Comment by Fallen-Breath** [comment]
因无法复现，且未提供更多有效信息，而关闭此 issue

**Comment by asgfdahahbds** [comment]
经过测试 发现当关闭OMMC的parsewaypointfromchat功能可解决这一问题
