### ISSUE TITLE
希望可以为配置文件中的source_root项提供通过读取mcdr的config动态获取工作目录的选项

### ISSUE THREAD

**Issue by NishikiAsumi0** [TISUnion/PrimeBackup#15]
在更换使用的服务端的时候，除了修改mcdr的工作目录还要同步修改pb的配置文件。希望可以添加可选项，在备份的时候，通过mcdr的接口获取当前的工作目录作为source_root

**Comment by Fallen-Breath** [comment]
对于这种经常切换 MCDR 工作路径的场景，建议将 MCDR 的工作路径设置为一个符号链接，这样即可无需更改任何配置文件（MCDR 的、PB 的）中的内容，即可仅在文件系统层面切换所需要的工作目录

下图是一个文件结构的例子，其中工作路径为 `server`

```
mcdr_root/
  server -> server_a
  server_a/
  server_b/
  server_c/
```
