### ISSUE TITLE
无法创建备份

### ISSUE THREAD

**Issue by Viomeat** [TISUnion/PrimeBackup#23]
[MCDR] [16:39:21] [PB@5bbb-worker-heavy/INFO] [prime_backup]: [PB] 创建备份中...请稍等
[Server] [16:39:21] [Server thread/INFO] [minecraft/MinecraftServer]: Automatic saving is now disabled
[Server] [16:39:21] [Server thread/INFO] [minecraft/MinecraftServer]: Saving the game (this may take a moment!)
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (lost_memory): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (maze): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (dungeon_dimension): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (bowels): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (corn_dimension): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (build_dimension): All chunks are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: Saved the game
[MCDR] [16:39:22] [PB@5bbb-worker-heavy/INFO] [prime_backup]: Creating backup for ['world'] at path 'server', timestamp 1713602362180962500, creator 'player:Yueguang_', comment '', tags {}
[MCDR] [16:39:22] [PB@5bbb-worker-heavy/ERROR] [prime_backup]: Task <prime_backup.mcdr.task.backup.create_backup_task.CreateBackupTask object at 0x0000020163766460> run error
Traceback (most recent call last):
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\mcdr\task_manager.py", line 74, in run_task
    ret = holder.task.run()
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\mcdr\task\backup\create_backup_task.py", line 51, in run
    backup = action.run()
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\action\create_backup_action.py", line 553, in run
    raise e
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\action\create_backup_action.py", line 533, in run
    query = gen.send(value)
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\action\create_backup_action.py", line 464, in __create_file
    query = gen.send(None)
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\action\create_backup_action.py", line 437, in __get_or_create_blob
    query = gen.send(None)
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\action\create_backup_action.py", line 329, in attempt_once
    blob_hash = hash_utils.calc_file_hash(src_path)
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\utils\hash_utils.py", line 46, in calc_file_hash
    return calc_file_size_and_hash(path, **kwargs).hash
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\utils\hash_utils.py", line 38, in calc_file_size_and_hash
    return calc_reader_size_and_hash(f, **kwargs)
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\utils\hash_utils.py", line 31, in calc_reader_size_and_hash
    while reader.read(buf_size):
  File "plugins\PrimeBackup-v1.7.3.pyz\prime_backup\utils\bypass_io.py", line 21, in read
    data = self.file_obj.read(*args, **kwargs)
PermissionError: [Errno 13] Permission denied
[Server] [16:39:22] [Server thread/INFO] [minecraft/MinecraftServer]: Automatic saving is now enabled

**Comment by Fallen-Breath** [comment]
注意到错误显示为 `PermissionError: [Errno 13] Permission denied`，请确保创建备份的存档文件夹内是否存在无权访问的文件

不过由于日志没有输出是哪个文件导致了失败，不太好进行进一步分析。你可以升级 PB 到 v1.7.4 以上的版本看看，新版 PB 在出现错误的时候会输出是哪个文件导致的失败

**Comment by Viomeat** [comment]
版本为1.7.4
文件夹为新创建的 并且已经修改config
[MCDR] [18:38:20] [TaskExecutor/INFO] [prime_backup]: 配置文件已加载
[MCDR] [18:38:20] [PB@06cb-worker-heavy/INFO] [prime_backup]: Worker heavy started
[MCDR] [18:38:20] [PB@06cb-worker-light/INFO] [prime_backup]: Worker light started
[MCDR] [18:38:20] [PB@06cb-crontab-scheduler/INFO] [prime_backup]: Scheduler started
[MCDR] [18:38:20] [TaskExecutor/INFO] [prime_backup]: Added job "CreateDbBackupJob.run" to job store "default"
[MCDR] [18:38:20] [TaskExecutor/INFO] [prime_backup]: Added job "PruneBackupJob.run" to job store "default"
[MCDR] [18:38:20] [TaskExecutor/INFO] [prime_backup]: Added job "VacuumSqliteJob.run" to job store "default"
[MCDR] [18:38:20] [TaskExecutor/INFO]: 共加载: 1 个插件; 共卸载: 1 个插件; 依赖检查失败: 2 个插件; 已加载插件数: 10
[MCDR] [18:38:20] [TaskExecutor/INFO] [prime_backup]: Found existing valid data of the previous online player counter, inherit it
> !!qb
[Server] [18:38:23] [Server thread/INFO] [minecraft/MinecraftServer]: Unknown or incomplete command, see below for error
[Server] [18:38:23] [Server thread/INFO] [minecraft/MinecraftServer]: !!qb<--[HERE]
> !!qb make
[Server] [18:38:26] [Server thread/INFO] [minecraft/MinecraftServer]: Unknown or incomplete command, see below for error
[Server] [18:38:26] [Server thread/INFO] [minecraft/MinecraftServer]: !!qb make<--[HERE]
> !!pb make
[MCDR] [18:38:28] [PB@06cb-worker-heavy/INFO] [prime_backup]: [PB] 创建备份中...请稍等
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: Automatic saving is now disabled
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: Saving the game (this may take a moment!)
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (lost_memory): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (maze): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (dungeon_dimension): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (bowels): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (corn_dimension): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage (build_dimension): All chunks are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: Saved the game
[MCDR] [18:38:28] [PB@06cb-worker-heavy/INFO] [prime_backup]: Creating backup for ['world'] at path 'server', timestamp 1713609508649106300, creator 'console:', comment '', tags {}
[MCDR] [18:38:28] [PB@06cb-worker-heavy/ERROR] [prime_backup]: Create blob for file 'server/world/data/biomancy.spatial.db' failed: [Errno 13] Permission denied
[Server] [18:38:28] [Server thread/INFO] [minecraft/MinecraftServer]: Automatic saving is now enabled
[MCDR] [18:38:28] [PB@06cb-worker-heavy/ERROR] [prime_backup]: Task <prime_backup.mcdr.task.backup.create_backup_task.CreateBackupTask object at 0x0000020164FDEDF0> run error
Traceback (most recent call last):
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\mcdr\task_manager.py", line 74, in run_task
    ret = holder.task.run()
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\mcdr\task\backup\create_backup_task.py", line 51, in run
    backup = action.run()
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\action\create_backup_action.py", line 556, in run
    raise e
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\action\create_backup_action.py", line 536, in run
    query = gen.send(value)
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\action\create_backup_action.py", line 467, in __create_file
    query = gen.send(None)
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\action\create_backup_action.py", line 437, in __get_or_create_blob
    query = gen.send(None)
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\action\create_backup_action.py", line 329, in attempt_once
    blob_hash = hash_utils.calc_file_hash(src_path)
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\utils\hash_utils.py", line 46, in calc_file_hash
    return calc_file_size_and_hash(path, **kwargs).hash
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\utils\hash_utils.py", line 38, in calc_file_size_and_hash
    return calc_reader_size_and_hash(f, **kwargs)
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\utils\hash_utils.py", line 31, in calc_reader_size_and_hash
    while reader.read(buf_size):
  File "plugins\PrimeBackup-v1.7.4.pyz\prime_backup\utils\bypass_io.py", line 21, in read
    data = self.file_obj.read(*args, **kwargs)
PermissionError: [Errno 13] Permission denied
[MCDR] [18:38:28] [PB@06cb-worker-heavy/INFO]: [PB] 任务创建备份执行失败, 见控制台以了解错误详情

**Comment by Viomeat** [comment]
补充一下 服务端核心为forge 1.19.2

**Comment by Fallen-Breath** [comment]
可发现，PB 无法读取的文件路径为 `server/world/data/biomancy.spatial.db`，这可能是一个非原版模组的数据库，在模组使用数据库的过程中其他程序无法读取该文件

该权限问题并非是 PB 能处理的，可能的解决方案有：

1. 在配置文件的 [ignored_files](https://tisunion.github.io/PrimeBackup/zh/config/#ignored_files) 选项中增加 `biomancy.spatial.db`，让 PB 备份时忽略该文件
2. 移除使用 `biomancy.spatial.db` 的模组，进而移除该文件
3. 切换操作系统至 linux，借助 linux 提供的文件系统来缓解文件被独占问题

**Comment by Viomeat** [comment]
已解决 感谢
