### ISSUE TITLE
备份时报错playerdata拒绝访问

### ISSUE THREAD

**Issue by maikuaidoufu** [TISUnion/PrimeBackup#25]
（从前有过使用QBM备份时区块位置错乱的情况，用相关工具替换过区块）后来好像是自从热替换了playerdata文件，使用QBM和PrimeBackup回档时（QBM在备份时就会报错，PrimeBackup在替换完存档后删除原来世界的playerdata文件时报错）报错内容是playerdata拒绝访问（WinError5）
[MCDR.log](https://github.com/TISUnion/PrimeBackup/files/15238592/MCDR.log)

**Comment by Fallen-Breath** [comment]
同 https://github.com/Fallen-Breath/MCDReforged/issues/303#issuecomment-2098864870，建议检查你的系统的运行环境，环境问题并不是本插件可以解决的

可以尝试在一个完全新建的 MCDR + 服务端里复现该问题

**Comment by maikuaidoufu** [comment]
> 同 [Fallen-Breath/MCDReforged#303 (comment)](https://github.com/Fallen-Breath/MCDReforged/issues/303#issuecomment-2098864870) ，建议检查你的系统的运行环境，环境问题并不是本插件可以解决的
> 
> 可以尝试在一个完全新建的 MCDR + 服务端里复现该问题

我换了一个存档就不报错了，我敢肯定是我那个存档的问题，但是我找不到问题，我把playerdata文件删了再备份也照样报错

**Comment by maikuaidoufu** [comment]
如果我什么都不更换只更换新的存档就不会报错，如果除了存档和必要的服务器核心和libraries文件其他都换，甚至换了电脑和新安装了mcdr也照样报错

**Comment by maikuaidoufu** [comment]
我把存档发出来？或者整个服务端？已经几乎不可能是环境的问题了，就是存档本身的问题

**Comment by Fallen-Breath** [comment]
若你愿意，可以发一下最小的可复现环境。记得去除无关文件

**Comment by maikuaidoufu** [comment]
除了python环境是3.12.3 64bit和java环境是java17.0.8 64bit，其他的都在文件里，但是压缩包1.88G发不出来，没压缩之前3.几个G但是存档就2.9G了

**Comment by maikuaidoufu** [comment]
我发网盘？

**Comment by Fallen-Breath** [comment]
若要打包发送环境，则请自行解决如何发送的问题；若无法发送环境，则请直接说明

**Comment by maikuaidoufu** [comment]
环境没法发，服务端太大了我发网盘

**Comment by maikuaidoufu** [comment]
链接：https://pan.baidu.com/s/1uFbdJDvw4HGA85YO-Yfanw?pwd=4a1b 
提取码：4a1b

**Comment by maikuaidoufu** [comment]
看见了能回复一下不

**Comment by maikuaidoufu** [comment]
能复现吗

**Comment by Fallen-Breath** [comment]
已复现该 issue，问题为：

- `world/playerdata` 文件夹的 mode 为 `16749`（`dr-xr-xr-x`）
- `world/playerdata` 中存在一个名为 `desktop.ini` 的文件

这导致 windows 将该 `world/playerdata` 设置成了某种特殊状态，并使 `desktop.ini` 无法被 python 的 `os.listdir` 检测

解决方法：

- 删除 `world/playerdata/desktop.ini`。同时请确保 `world` 下的其他文件夹中也不能存在类似的 `desktop.ini`
- （可选）重新创建存档下的所有文件夹，确保其 mode 均为默认值

**Comment by Fallen-Breath** [comment]
确认该 issue 与本插件无关
