### ISSUE TITLE
[增强]更大数量的批量删除

### ISSUE THREAD

**Issue by ailixiyaX** [TISUnion/PrimeBackup#28]
mc的输入栏能输入的字数有限（<128）
但自动备份时间久了往往会产生上千个备份
这样删除起来十分麻烦
所以可以加一个批量删除
如：!!pb delete 11 4514（本人英语不好 用的是原来删除多个指定备份的指令）

**Comment by Fallen-Breath** [comment]
请定义所述“批量删除”的表现，并给出为何已有的 `!!pb delete`（支持输入多个 ID）、`!!pb delete_rage`（支持范围删除）、备份清理配置，无法满足所述需求

**Comment by ailixiyaX** [comment]
范围进行清除
如想要从备份id从 "10"到"1000"中包含的备份全部删除

**Comment by Fallen-Breath** [comment]
所述功能已存在，使用 `!!pb delete_range 10-1000` 即可
