### ISSUE TITLE
「功能请求」远程备份

### ISSUE THREAD

**Issue by d0j1a1701** [TISUnion/PrimeBackup#29]
如题，望支持 SFTP/FTP 将备份文件（压缩到单文件）/文件夹上传到远程服务器。

若能直接接入部分网盘 API 则好上加好。

**Comment by Fallen-Breath** [comment]
暂不考虑支持

**Comment by d0j1a1701** [comment]
好吧，那请问能实现一个定时将最新备份输出为单文件功能吗，因为单文件输出功能似乎已在 CLI 中实现

**Comment by Fallen-Breath** [comment]
也不考虑实现。这一类自定义需求完全可以通过外部脚本实现

**Comment by d0j1a1701** [comment]
如果正在创建备份时通过外部脚本导出了备份数据会出事吗

**Comment by Fallen-Breath** [comment]
> 如果正在创建备份时通过外部脚本导出了备份数据会出事吗

不会
