### ISSUE TITLE
多线程压缩/解压

### ISSUE THREAD

**Issue by ph59x** [TISUnion/PrimeBackup#3]
在创建备份/回档时，可以多线程压缩/解压数据文件吗？如果可以，如何调整相关设置（比如线程数）

**Comment by Fallen-Breath** [comment]
暂不支持

**Comment by Fallen-Breath** [comment]
v1.6.0 版本已支持创建备份时的多线程哈希预扫描，以及回档时的多线程解压

创建备份的压缩储存新文件的流程由于比较复杂，需要考虑的情况很多，暂时仍不支持多线程。不过在实际使用场景下，新备份基本上不会有很多新增的备份文件，因此这部分无法并行处理的影响不大
