### ISSUE TITLE
【功能请求】使用命令行工具一键回档

### ISSUE THREAD

**Issue by cacheci** [TISUnion/PrimeBackup#36]
## 建议：添加使用命令行工具一键回档的功能
用途：在档完全炸了的情况下方便的回档
具体案例：`export 82 --back server/world`，备份 server/world 文件夹至 server/world.bak 并用 82 号备份覆写 server/world 文件夹

**Comment by Fallen-Breath** [comment]
请阐述目前 PB 命令行工具的 `extract` 为何无法实现所提及功能

```
python PrimeBackup-v1.7.4.pyz extract 82 -r -o server/world .
```

**Comment by Fallen-Breath** [comment]
除此之外，请注意 PB 的命令行工具并不理解“回档”这一概念，因为命令行运行环境中缺少 MCDR / 服务器运行状态的上下文。因此，若需要执行所述回档操作，你需要在 `extract` 子命令提取文件前，手动清理已存在的存档文件

**Comment by cacheci** [comment]
不好意思，是我看文档的时候疏忽了，想当然以为`extract`是用来提取某个备份中单个文件的。有`extract`功能的话用来回档应该是没问题了。

**Comment by Fallen-Breath** [comment]
看了下，CLI 的帮助信息输出确实存在不准确的现象，之后调整修复下

https://github.com/TISUnion/PrimeBackup/blob/07e78e0b90a7126dd95c949fb33061b5a048f701/prime_backup/cli/cli_entrypoint.py#L309-L310
