### ISSUE TITLE
问题：创建备份时temp_file_path为空导致创建失败

### ISSUE THREAD

**Issue by liuyao0** [TISUnion/PrimeBackup#39]
**环境**:
Ubuntu 22.04.4
Python 3.12.1
MCDReforged 2.13.1
PrimeBackup 1.8.0
服务端 fabric-server-mc.1.21-loader.0.16.0-launcher.1.0.1.jar
**表现**:
PrimeBackup配置完成后执行!!pb make，提示备份创建失败，控制台输出如下

> > !!pb make
> [MCDR] [16:56:06] [PB@e27d-worker-heavy/INFO] [prime_backup]: [PB] 创建备份中...请稍等
> [Server] [16:56:06] [Server thread/INFO]: Automatic saving is now disabled
> [Server] [16:56:06] [Server thread/INFO]: Saving the game (this may take a moment!)
> [Server] [16:56:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
> [Server] [16:56:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
> [Server] [16:56:06] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
> [Server] [16:56:06] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
> [Server] [16:56:06] [Server thread/INFO]: Saved the game
> [MCDR] [16:56:06] [PB@e27d-worker-heavy/INFO] [prime_backup]: Creating backup for ['world'] at path 'server', file cnt 238, timestamp 1721638566154357451, creator 'console:', comment '', tags {}
> [MCDR] [16:56:06] [PB@e27d-worker-heavy/ERROR] [prime_backup]: Create blob for file 'server/world/region/r.0.0.mca' failed: expected str, bytes or os.PathLike object, not NoneType
> [MCDR] [16:56:06] [PB@e27d-worker-heavy/WARNING] [prime_backup]: Error occurs during import, applying rollback
> [MCDR] [16:56:06] [PB@e27d-worker-heavy/ERROR] [prime_backup]: Task <prime_backup.mcdr.task.backup.create_backup_task.CreateBackupTask object at 0x762fb101d550> run error
> Traceback (most recent call last):
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/mcdr/task_manager.py", line 74, in run_task
>     ret = holder.task.run()
>           ^^^^^^^^^^^^^^^^^
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/mcdr/task/backup/create_backup_task.py", line 51, in run
>     backup = action.run()
>              ^^^^^^^^^^^^
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/action/create_backup_action.py", line 596, in run
>     raise e
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/action/create_backup_action.py", line 576, in run
>     query = gen.send(value)
>             ^^^^^^^^^^^^^^^
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/action/create_backup_action.py", line 509, in __create_file
>     query = gen.send(result)
>             ^^^^^^^^^^^^^^^^
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/action/create_backup_action.py", line 479, in __get_or_create_blob
>     query = gen.send(result)
>             ^^^^^^^^^^^^^^^^
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/action/create_backup_action.py", line 420, in attempt_once
>     cr = compressor.copy_compressed(src_path, temp_file_path, calc_hash=True)
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "plugins/PrimeBackup-v1.8.0.pyz/prime_backup/compressors.py", line 45, in copy_compressed
>     with open(source_path, 'rb') as f_in, open(dest_path, 'wb') as f_out:
>                                           ^^^^^^^^^^^^^^^^^^^^^
> TypeError: expected str, bytes or os.PathLike object, not NoneType
> [MCDR] [16:56:06] [PB@e27d-worker-heavy/INFO]: [PB] 任务创建备份执行失败, 见控制台以了解错误详情
> [Server] [16:56:06] [Server thread/INFO]: Automatic saving is now enabled
> >

**note**:
其余环境不变，降级使用PrimeBackup 1.7.4，可以正常创建备份。观察代码应该是调用compressor.copy_compressed(src_path, temp_file_path, calc_hash=True)时传入的temp_file_path为空，为temp_file_path赋值的代码为create_backup_action.py中的
`with make_temp_file() as temp_file_path:`
1.7.4版本中make_temp_file()定义为
```
		@contextlib.contextmanager
		def make_temp_file() -> ContextManager[Path]:
			temp_file_name = f'blob_{os.getpid()}_{threading.current_thread().ident}_{src_path_md5}.tmp'
			temp_file_path = self.__temp_path / temp_file_name
			with contextlib.ExitStack() as exit_stack:
				exit_stack.callback(functools.partial(self._remove_file, temp_file_path))
				yield temp_file_path

```
1.8.0版本中定义为

> 		@contextlib.contextmanager
> 		def make_temp_file() -> ContextManager[Path]:
> 			temp_file_name = f'blob_{os.getpid()}_{threading.current_thread().ident}_{src_path_md5}.tmp'
> 			temp_file_path = self.__temp_path / temp_file_name
> 			try:
> 				yield
> 			finally:
> 				self._remove_file(temp_file_path, what='temp_file')
貌似是1.8.0版本中没有写返回值？

另感谢您对Minecraft生态的贡献！

**Comment by Fallen-Breath** [comment]
奇怪，为什么测试的时候没问题，可能是提交的时候把这个给不小心删了

**Comment by liuyao0** [comment]
在1.8.0中yield改成yield temp_file_path后可以成功创建备份了，但是没有测试其他方面有没有问题
