### ISSUE TITLE
回档保存世界报错

### ISSUE THREAD

**Issue by SnubSum31041247** [TISUnion/PrimeBackup#43]
[MCDR] [10:34:35] [MainThread/ERROR]: 解析文本 b"[10:34:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[\xb3\xac\xc6\xbd\xcc\xb9]'/minecraft:overworld\r\n" 出错: {'utf8': UnicodeDecodeError('utf-8', b"[10:34:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[\xb3\xac\xc6\xbd\xcc\xb9]'/minecraft:overworld\r\n", 70, 71, 'invalid start byte')}
[MCDR] [10:34:35] [MainThread/ERROR]: 解析文本 b"[10:34:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[\xb3\xac\xc6\xbd\xcc\xb9]'/minecraft:the_end\r\n" 出错: {'utf8': UnicodeDecodeError('utf-8', b"[10:34:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[\xb3\xac\xc6\xbd\xcc\xb9]'/minecraft:the_end\r\n", 70, 71, 'invalid start byte')}
[MCDR] [10:34:35] [MainThread/ERROR]: 解析文本 b"[10:34:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[\xb3\xac\xc6\xbd\xcc\xb9]'/minecraft:the_nether\r\n" 出错: {'utf8': UnicodeDecodeError('utf-8', b"[10:34:35] [Server thread/INFO]: Saving chunks for level 'ServerLevel[\xb3\xac\xc6\xbd\xcc\xb9]'/minecraft:the_nether\r\n", 70, 71, 'invalid start byte')}

**Comment by SnubSum31041247** [comment]
T_T

**Comment by SnubSum31041247** [comment]
[MCDR] [10:40:31] [MainThread/ERROR]: 解析文本 b'[10:40:31] [Server thread/INFO]: \xc6\xf4\xb6\xaf Floodgate\xa3\xac\xba\xc4\xca\xb143ms\r\n' 出错: {'utf8': UnicodeDecodeError('utf-8', b'[10:40:31] [Server thread/INFO]: \xc6\xf4\xb6\xaf Floodgate\xa3\xac\xba\xc4\xca\xb143ms\r\n', 33, 34, 'invalid continuation byte')}

**Comment by Fallen-Breath** [comment]
MCDR 配置错误，与本插件无关。请正确配置 MCDR 的编码 / 解码方式
