### ISSUE TITLE
Add mcdr event support

### ISSUE THREAD

**Issue by z0z0r4** [TISUnion/PrimeBackup#48]
As QuickBackupM and TimedQBM, extension plugin requires mcdr events.

**Comment by Fallen-Breath** [comment]
What types of extension plugins need to receive what events in which scenarios? Please list the events you want PB to provide, along with the corresponding use case scenarios, rather than just a vague issue description

**Comment by z0z0r4** [comment]
In my case, the backup is done offsite at the same time, which may not be suitable for primebackup and requires an extension plugin

This will listen to the create backup event and trigger the export event

**Comment by z0z0r4** [comment]
Noticed that the export operation cannot specify the export path by itself. I will submit a new issue

https://github.com/TISUnion/PrimeBackup/issues/49

**Comment by z0z0r4** [comment]
https://github.com/TISUnion/PrimeBackup/pull/50

**Comment by z0z0r4** [comment]
> What types of extension plugins need to receive what events in which scenarios? Please list the events you want PB to provide, along with the corresponding use case scenarios, rather than just a vague issue description

我需要
```python
# events
BACKUP_DONE_EVENT
DELETE_DONE_EVENT
EXPORT_DONE_EVENT
IMPORT_DONE_EVENT
TRIGGER_BACKUP_EVENT
TRIGGER_DELETE_EVENT
TRIGGER_EXPORT_EVENT
TRIGGER_IMPORT_EVENT
```

以及可能需要
```python
RESTORE_DONE_EVENT
TRIGGER_RESTORE_EVENT
```

**Comment by z0z0r4** [comment]
很明显，对于一个将备份上传到云端的扩展，需要在 `BACKUP_DONE_EVENT` 时上传新备份、`DELETE_DONE_EVENT` 删除不需要的备份、需要在 `IMPORT_DONE_EVENT` 时上传导入的备份，需要 `TRIGGER_EXPORT_EVENT` 来导出备份以上传，需要 `EXPORT_DONE_EVENT` 回报上传完成。其他的是非必须的

**Comment by Fallen-Breath** [comment]
对于这一具体需求，我不建议以备份为粒度，将数据保存至云端。以备份为粒度进行上传，将无法利用 PB 的文件粒度去重逻辑，导致额外占用很多空间。请仔细思考确认这是否是一个合理的需求实现。我个人的建议是，直接把 PB 的 pb_files 路径定时全量同步至云端即可

对于具体对 PB 增加 event 的 feature request 里，那些主动触发 PB 的 task 的需求，这并不适合使用 MCDR 的 event 来进行，更应该直接使用 PB 提供的 API 接口来触发。相关 API 接口也已在 TODO list 里了

**Comment by Fallen-Breath** [comment]
> http 既没有着落，也没有标准可循

这里的 http 是什么意思？该 issue 的上下文中并未出现任何与之相关的信息

如果你对这里的 http 有思考想法，也可以详细解释一下；如果你只是在自言自语，可以忽略此回复

**Comment by z0z0r4** [comment]
> > http 既没有着落，也没有标准可循
> 
> 这里的 http 是什么意思？该 issue 的上下文中并未出现任何与之相关的信息
> 
> 如果你对这里的 http 有思考想法，也可以详细解释一下；如果你只是在自言自语，可以忽略此回复

![Screenshot_20241201_074134.jpg](https://github.com/user-attachments/assets/099840b3-4166-418a-8ab7-79fd9e74ab07)

似乎你打算用 http 来做扩展支持

**Comment by z0z0r4** [comment]
> 对于这一具体需求，我不建议以备份为粒度，将数据保存至云端。以备份为粒度进行上传，将无法利用 PB 的文件粒度去重逻辑，导致额外占用很多空间。请仔细思考确认这是否是一个合理的需求实现。我个人的建议是，直接把 PB 的 pb_files 路径定时全量同步至云端即可
> 
> 对于具体对 PB 增加 event 的 feature request 里，那些主动触发 PB 的 task 的需求，这并不适合使用 MCDR 的 event 来进行，更应该直接使用 PB 提供的 API 接口来触发。相关 API 接口也已在 TODO list 里了

如果是上传文件池，自然不需要额外插件…但我的预期是能直接把备份拿出来用，上传大量小文件也不方便，特别是网盘

相关 api 接口指的是 todo 里面的 http 支持？

**Comment by z0z0r4** [comment]
> 对于具体对 PB 增加 event 的 feature request 里，那些主动触发 PB 的 task 的需求，这并不适合使用 MCDR 的 event 来进行，更应该直接使用 PB 提供的 API 接口来触发。相关 API 接口也已在 TODO list 里了

主动触发不论，但被动触发的需求没 event 不行吧

**Comment by z0z0r4** [comment]
我不做了…草，感觉都成写议论文了…我没本事，close 了
