### ISSUE TITLE
Export operation supports custom export path

### ISSUE THREAD

**Issue by z0z0r4** [TISUnion/PrimeBackup#49]
https://github.com/TISUnion/PrimeBackup/issues/48, the extension should have the right to customize the export path?

To avoid copying again and taking up disk space...

This is very meaningful

**Comment by Fallen-Breath** [comment]
If you want the `!!pb export` command to have the ability to customize export path, please create a new issue

**Comment by z0z0r4** [comment]
Hmm, does this mean I should create an issue about public APIs?

**Comment by Fallen-Breath** [comment]
> Hmm, does this mean I should create an issue about public APIs

It's already in the todo list, but yeah you can still create an issue for it

> My needs are as you can see

I don't see what your need are

> I don't have much time to wait

Then you should create a fork
