### ISSUE TITLE
Issue Loading Plugin on Server - TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by fuarthur** [TISUnion/PrimeBackup#8]
**Issue Description:**
When attempting to load the plugin(using !!MCDR plg load) on my server, I encountered an error with the following message: `TypeError: 'type' object is not subscriptable`. I have attached the detailed error message in the file `error_message.txt`.

**Environment Information:**
- MCDReforged version: 2.12.3
- Python Version: Python 3.8
- Server OS: Ubuntu 20.04.5 LTS (Focal Fossa)

**Additional Context:**
- Verified the presence of all required dependencies and their versions.
- Confirmed that the configuration directory and files for the plugin do not exist in the `config` directory.

**Error Message:**
Please refer to the attached `error_message.txt` file for the detailed error message.

**Attachments:**
- [error_message.txt](https://github.com/TISUnion/PrimeBackup/files/13759017/error_message.txt)

**Comment by Fallen-Breath** [comment]
Fixed in v1.6.1
