### ISSUE TITLE
备份询问

### ISSUE THREAD

**Issue by SainT194555** [TISUnion/PrimeBackup#9]
进行备份后，该备份新增文件的原始总体积（括号里的体积）是+7G左右，而每次备份完后，该备份的原始总体积总是10G左右,询问内容为：这是正常的么？我以为备份新增文件的原始总体积（括号里的体积）是改变了的内容，体积应该不会这么大。服务器使用机械硬盘。
![{A59B1C23-48AB-47f1-A358-EC2EB8340E3B}](https://github.com/TISUnion/PrimeBackup/assets/143593357/659e3a23-3c86-493f-a940-cf688c958847)
![image](https://github.com/TISUnion/PrimeBackup/assets/143593357/a7800c59-bafc-4959-b76f-878d1c855d3a)

**Comment by Fallen-Breath** [comment]
括号内的体积确实是新增数据的体积

正常来说，除非服务器文件全部发生变化，或者执行了大范围跑图加载等操作，否则不应该会有增加接近存档体积的数据的情况出现

如果这不符合预期，你可以通过下述手段排查问题：

- 查看异常备份创建时的相关日志，看看是否真的新增了非常多的blob数量
- 使用 `!!pb overview` 查看全部备份数据占用总空间。如果去重能正常运行，应该不会超出单个存档大小的太多倍。这一步也可以手动统计 pb_files 文件夹的空间大小来辅助判断
- 注意到你展示的备份 76 和 77 直接备份体积增幅差异很大，这意味着所述问题不是必现的。你可以将异常备份，和其之前的一个备份（比如备份 75）做对比，看看变化的文件是否符合预期
  你可以用 `!!pb diff 75 76` 来查看两个备份之间的差异，这个指令建议输出可能较多，建议在控制台执行。如果在 mc 客户端执行，那可能需要翻日志来看输出了什么。指令执行完后，你可以用 `!!pb database inspect` 来分析差异文件袋具体状况

**Comment by SainT194555** [comment]
**1**.非常抱歉，我只找到了pb_files/logs，其中db.log为空，prune.log的内容我认为没有用
![{28176BC2-23A1-4bb2-B708-24082E920C3C}](https://github.com/TISUnion/PrimeBackup/assets/143593357/872e3115-4cb4-4da1-a494-2ca6d24e7a1e)
**2**.pb_files的体积我认为是合理的，不过 !!pb overview 指令不能正常使用，或许是我的问题
![1579b61b05b8b168b7b5765ea392a2b0](https://github.com/TISUnion/PrimeBackup/assets/143593357/8b04b543-0674-49a0-98e6-475b91a9726d)
![ecec2b31ce6a1763e8fec017087e29f5](https://github.com/TISUnion/PrimeBackup/assets/143593357/4efc0649-521b-4bba-a8ce-550174af6b67)
![52514bcb348c7d4c0359ba77545338f2](https://github.com/TISUnion/PrimeBackup/assets/143593357/c0f4dc89-9646-41a1-a422-8793054c0d76)
**3**.三个备份79、80、81期间没有玩家进行活动，79、80之间时间间隔较大，而80、81间隔较小，其他条件相同（#79备份时间为11点 #80备份时间11点10分  #81备份时间 11点14），我认为是时间影响了备份大小，连续备份则正常，但是不知道为什么。
![04f5989c90ac7c90d337fe155bf84430](https://github.com/TISUnion/PrimeBackup/assets/143593357/e1f1748b-3155-4d6a-bd6f-cb6055d68014)
![e9701fdf859b917031599a1751574ddf](https://github.com/TISUnion/PrimeBackup/assets/143593357/b322c8ea-8848-49fd-becc-7782d8c10959)
![6bf59a930b20e89a9c941051c1ead4c5](https://github.com/TISUnion/PrimeBackup/assets/143593357/0cd0f7b4-a34a-4e9f-add1-be142acc0b8a)
![d09c3f60c4c8325ed765bc27797dd094](https://github.com/TISUnion/PrimeBackup/assets/143593357/c6038cd2-5a4f-436f-be8d-63f515f16107)
![6a874ac60eda5052da0a49d924e1d396](https://github.com/TISUnion/PrimeBackup/assets/143593357/25b3f4ac-ccda-4414-bb72-b854115c9b18)
![image](https://github.com/TISUnion/PrimeBackup/assets/143593357/29649fcf-dd31-421a-b874-8802a2572dc1)

感谢佛冷大大，让我们从2分多钟备份时间缩减到不到1分钟，:)

**Comment by Fallen-Breath** [comment]
上面评论指令有误，`!!pb overview` 应该为 `!!pb database overview`

对于需要 diff 比较的备份，请注意我在上述评论中提及的操作方式：比较异常的备份（如 id 76）和其之前的最近一个备份（如 id 75，若存在），而不是随便挑两个备份来比较。因为这是在分析为什么异常备份会有怎么多的新增文件

**Comment by Fallen-Breath** [comment]
对于备份 79、80、81 这三个备份的情况，你可以检查下这 3 个备份两两间备份的 `!!pb diff` 输出，看看 diff 输出的文件列表有什么差异，diff 输出的那些文件是否真的有大文件。可以借助 `!!pb database inspect file` 查看备份文件的具体信息

**Comment by Fallen-Breath** [comment]
对于 https://github.com/TISUnion/PrimeBackup/issues/9#issuecomment-1869211682 这里指的日志，指的是 mcdr 的日志

**Comment by SainT194555** [comment]
经过对比，发现了罪魁祸首，是某个模组。
卸载后多次实验，已经可以正常备份了！
代表本服务器玩家感谢大佬让服务器的备份速度快了近十倍！~
正如五星上将麦克阿瑟说过：如果生电圈没有诸位大佬的贡献，那么我们仍处于原始时代。
再次感谢~

**Comment by Fallen-Breath** [comment]
> 经过对比，发现了罪魁祸首，是某个模组。 卸载后多次实验，已经可以正常备份了！ 

如果方便的话，也可以在这里提供下具体是什么模组，做了什么东西，从而影响了备份。这一如果其他用户也有类似问题的话，也可以以此作为参考

**Comment by SainT194555** [comment]
好的，因为我们使用树场的时候多次发现缺少零件，初步怀疑人为故意破坏导致.......（其实是太笨了，操作失误），于是添加了一个查熊模组：**ledger**，这个模组会在world文件里生成一个名为**ledger.sqlite**的文件，我猜测是记录数据的，体积刚刚好是7.09G，再加上地图的更新体积，就会导致每次备份都会出现这个问题。

**Comment by SainT194555** [comment]
> > 经过对比，发现了罪魁祸首，是某个模组。 卸载后多次实验，已经可以正常备份了！
> 
> 如果方便的话，也可以在这里提供下具体是什么模组，做了什么东西，从而影响了备份。这一如果其他用户也有类似问题的话，也可以以此作为参考
 
好的大佬，由于我们使用树场的时候多次发现缺少零件，所以怀疑是人为破坏.....（其实是太笨了，操作失误），于是就加了一个查熊模组：**ledger**，这个模组会在world文件里生成一个名为**ledger.sqlite**的文件，体积正好是7.09G，加上每次备份的地图体积变化，就导致了这个问题。

**Comment by AnzhiZhang** [comment]
> 这个模组会在world文件里生成一个名为**ledger.sqlite**的文件

ledger 是记录玩家行为的，建议使用插件的配置把 ledger 数据库排除在备份文件外，手动备份此文件（QB 是有这个功能的，不清楚 PB 有没有）。另外，插件在使用数据库时被备份插件备份也容易导致数据库损坏。

**Comment by sileence114** [comment]
> > 这个模组会在world文件里生成一个名为**ledger.sqlite**的文件
> 
> ledger 是记录玩家行为的，建议使用插件的配置把 ledger 数据库排除在备份文件外，手动备份此文件（QB 是有这个功能的，不清楚 PB 有没有）。另外，插件在使用数据库时被备份插件备份也容易导致数据库损坏。
> 
> 如果 ledger 支持，也可以修改数据文件位置，放在服务器目录中。

我也遇到了增量过大的问题。经过排查存档内有一个2.3G的 `DistantHorizons.sqlite` ，是 [Distant Horizons](https://modrinth.com/mod/distanthorizons) mod 用于存放渲染数据的数据库文件。且翻遍配置文件无相关配置项。
在 `config.json` 内添加了
```
"ignore_patterns": [
  "world/data/DistantHorizons.sqlite",
  "**/session.lock"
]
```
```mcdr.log
> !!pb make
[MCDR] [18:00:31] [PB@12ff-worker-heavy/INFO] [prime_backup]: [PB] 创建备份中...请稍等
[Server] [18:00:31] [Server thread/INFO]: Automatic saving is now disabled
[Server] [18:00:31] [Server thread/INFO]: Saving the game (this may take a moment!)
[Server] [18:00:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [18:00:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [18:00:31] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [18:00:31] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[Server] [18:00:31] [Server thread/INFO]: Saved the game
[MCDR] [18:00:31] [PB@12ff-worker-heavy/INFO] [prime_backup]: Scanning file for backup creation at path 'server', targets: ['world']
[MCDR] [18:00:31] [PB@12ff-worker-heavy/INFO] [prime_backup]: Creating backup for ['world'] at path 'server', file cnt 1539, timestamp 1750586431427984047, creator 'console:', comment '', tags {}
[MCDR] [18:00:35] [PB@12ff-worker-heavy/INFO] [prime_backup]: Create backup #40 done, +4 blobs (size 1.09MiB / 2.17MiB)
[MCDR] [18:00:35] [PB@12ff-worker-heavy/INFO] [prime_backup]: Time costs: save wait 0.07s, create backup 4.69s
[MCDR] [18:00:36] [PB@12ff-worker-heavy/INFO] [prime_backup]: [PB] 备份完成, ID #40, 耗时4.76s, 体积1.89GiB (+2.17MiB)
[MCDR] [18:00:36] [PB@12ff-worker-heavy/INFO] [prime_backup]: [PB] 检测到新增的备份, 重置定时器。下次定时备份: 2025-06-22 19:00:43
[Server] [18:00:36] [Server thread/INFO]: Automatic saving is now enabled
> !!pb list
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] ======== 备份列表 ========
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] 共有6个备份:
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] [#40] [>] [x] 1.89GiB 2025-06-22 18:00:31: 空
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] [#39] [>] [x] 5.51GiB 2025-06-22 17:56:59: 空
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] [#38] [>] [x] 5.51GiB 2025-06-22 17:55:01: 空
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] [#37] [>] [x] 4.70GiB 2025-06-20 22:26:49: 定时备份
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] [#34] [>] [x] 4.18GiB 2025-06-19 20:21:31: 定时备份
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] [#12] [>] [x] 2.57GiB 2025-06-15 21:11:24: 定时备份
[MCDR] [18:01:53] [PB@12ff-worker-light/INFO]: [PB] <- 1/1 ->
```

注：该问题可能具有时效性，更改数据库存储位置 [已被提上issue](https://gitlab.com/distant-horizons-team/distant-horizons/-/issues/1032)
